# Generated by Django 4.0.5 on 2022-06-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('duration', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('credits', models.PositiveBigIntegerField()),
                ('teacher', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=35)),
                ('secondSurname', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=35)),
                ('birthDate', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1)),
                ('vigencia', models.BooleanField(default=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.career')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateEnrollment', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.student')),
            ],
        ),
    ]
